In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_sas('LLCP2015.XPT')



df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'LLCP2015.XPT'

In [4]:
df.columns.values.tolist()

NameError: name 'df' is not defined

In [4]:
# To pull needed columns only 


reduced_mental_health_data = df.loc[:, ['IDATE','_STATE', 'SEX', '_AGEG5YR', '_PRACE1', 'EMPLOY1', 'MSCODE',
                                        'MENTHLTH','POORHLTH','HLTHPLN1', 'SLEPTIM1','CVDINFR4', 
                                        'CVDCRHD4', 'CVDSTRK3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR',
                                        'CHCCOPD1','HAVARTH3','ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 
                                        'PREGNANT', 'DECIDE', 'DIFFALON', 'SMOKDAY2', 'ALCDAY5', 'MARIJANA',
                                        'EMTSUPRT', 'LSATISFY']]


reduced_mental_health_data.head()

,IDATE,_STATE,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,POORHLTH,HLTHPLN1,...,CHCKIDNY,DIABETE3,PREGNANT,DECIDE,DIFFALON,SMOKDAY2,ALCDAY5,MARIJANA,EMTSUPRT,LSATISFY
0,b'01072016',1.0,1.0,5.0,1.0,1.0,3.0,88.0,NaN,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
1,b'01112016',1.0,2.0,8.0,1.0,5.0,1.0,88.0,NaN,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
2,b'01062016',1.0,2.0,13.0,1.0,7.0,2.0,1.0,88.0,1.0,...,2.0,3.0,NaN,2.0,2.0,1.0,101.0,NaN,NaN,NaN
3,b'01082016',1.0,1.0,11.0,1.0,7.0,1.0,88.0,NaN,1.0,...,2.0,1.0,NaN,2.0,2.0,3.0,888.0,NaN,NaN,NaN
4,b'01052016',1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN

In [5]:
#TODO: Rename the COlumns based on sematic names 
#  ASTHMA3 since asks for prior conditions we just need ASTHNOW

#Then pull appropraiet column and store as XPT file and then upload it for 2016 under raw_data folder 

#TO - Write Function for 
#    1) Parsing Date Recorded 
#    2) Employment Status 
#    3) "MENTHLTH": "Mental_Health_Factor" - Number of Days Mental Health Issue - Interpret: a) 1-30 days (can be made into a decimal factor ). b) Interpret  88 as 0 days or 0 factor. c) Others as NaN (N/A)
#    4) "POORHLTH": Poor Health Factor - Interpret Similar to (3)   - The field indicates no. of days did poor physical or mental health keep you from doing your usual activities, such as self-care, work, or recreation
#    5) "HLTHPLN1" : "Health_Coverage" - Health Coverege - Interpret: a) 1 (Yes) b) 2 (No) c) 7 & 9  (NaN)
#    6) "SLEPTIM1" : "Sleep_Hours" - On average, how many hours of sleep do you get in a 24-hour period - Interpret a) 1-24 (same as original field values) , b) 77, 99, BLANK as (Nan)
#    7) "CVDINFR4" : "Chronic_HeartAttack" - Ever diagnosed with heart attack - Interpret as a) 1 (yes) b) 2 (no) c) 7,9,BLANK (NaN)
#    8) "CVDCRHD4" : "Chronic_CoronaryHeartDisease" - Interpret similar to (7) above  
#    9) "CVDSTRK3" : "Chronic_Stroke" - Interpret similar to (7) above 
#   10) "ASTHNOW"  : "Chronic_Asthma" - Interpret similar to (7) above 
#   11) "CHCSCNCR" : "Chronic_SkinCancer" - Interpret similar to (7) above
#   12) "CHCOCNCR" : "Chronic_OtherCancer" - Interpret similar to (7) above
#   13) "CHCCOPD1" : "Chronic_Pulmonary", - Interpret similar to (7) above
#   14) "HAVARTH3" : "Chronic_Arthritis", - Interpret similar to (7) above
#   15) "ADDEPEV2" : "Chronic_Depression", - Interpret similar to (7) above
#   16) "CHCKIDNY" : "Chronic_KidneyDisease", - Interpret similar to (7) above
#   17) "DIABETE3" : "Chronic_Diabetes", - Interpret similar to (7) above
#   18) "PREGNANT" : "Pregnant" - Interpret similar to (7) above 
#   19) "DECIDE"   : "Difficulty_ConcentrateMemoryDecision" - Interpret similar to (7) above
#   20) 'DIFFALON' : "Difficulty_ErrandsAlone",  - Interpret similar to (7) above
#   21) 'SMOKDAY2' : "Smoke_Frequency", Interpret as a) 1 - (Every Day) b) 2 - (Some Days) c) 3 - (None) d) 7,9, BLANK - (NaN)
#   22) "ALCDAY5"  : "Alcohol_Frequency",  Interpret a) 1 X Y - XY can be 00 to 07 indicate number of days per week they drink alcohol -> (1/7 or n/7 decimal factor) b) 2 A B - A B indicates no. of days ina month where alcohol consumed -> (1/30 or n/30 decimal factor) c) 777, 888, 999, BLANk -> (Nan) 
#   23) "MARIJANA" : "Marijuana_Usage", Interpret a) 1-30 - No. days used per month (1/30 or n/30 decimal factor) b) 88 - 0 Days -> (0 usage) c) 77,99, BLANK -> (NaN)
#   24) "EMTSUPRT" : "EmotionalSupport_Availability" - Interpret a) 1 - (Always) b) 2 - (Usually) c) 3 - (Sometimes) d) 4 - (Rarely) e) 5 - (Never) f) 7,9, BLANK - (NaN)
#   25) "LSATISFY" : "LifeSatisfaction_Level" - Interpret as a) 1 - (Very Satisfied) b) 2 (Satisfied) c) 3 (Dissatisfied) d) 4 (Very Dissatisfied) e) 7,9, BLANK - (NaN)
#   26) "SEX"      : "Gender" - Interpret as a) 1 - (Male)  b) 2 - (Female)  c) 9 - (NaN)
#   27) "_STATE"   : "State" - Interpret State based on Number to State Mapping
#   28) "_AGEG5YR" : "Age_Range" - Interpret based on Age Range Buckets (See below) 
#   29) "_PRACE1"  : "Race" - Interept based on Race Mappings 
#   30) "MSCODE"   : "MetroStatusCode" - Interpret a) 1, 2, 3 -> (Urban)  b) 5 as (Rural) c)  Other - (NaN)

# Age Buckets:  Interpret: 
# 1)   1  - (18-24)  Respondents with reported age between 18 and 24 years (18 <= AGE <= 24)
# 2)   2  - (25-29) Respondents with reported age between 25 and 29 years (25 <= AGE <= 29)
# 3)   3  - (30-34) Respondents with reported age between 30 and 34 years (30 <= AGE <= 34)
# 4)   4  - (35-39) Respondents with reported age between 35 and 39 years (35 <= AGE <= 39)
# 5)   5  - (40-44) Respondents with reported age between 40 and 44 years (40 <= AGE <= 44)
# 6)   6  - (45-49) Respondents with reported age between 45 and 49 years (45 <= AGE <= 49)
# 7)   7  - (50-54) Respondents with reported age between 50 and 54 years (50 <= AGE <= 54)
# 8)   8  - (55-59) Respondents with reported age between 55 and 59 years (55 <= AGE <= 59)
# 9)   9  - (60-64) Respondents with reported age between 60 and 64 years (60 <= AGE <= 64)
# 10) 10  - (65-69) Respondents with reported age between 65 and 69 years (65 <= AGE <= 69)
# 11) 11  - (70-74) Respondents with reported age between 70 and 74 years (70 <= AGE <= 74)
# 12) 12  - (75-79) Respondents with reported age between 75 and 79 years (75 <= AGE <= 79)
# 13) 13  - (80 or older) Respondents with reported age between 80 and 99 years (80 <= AGE <= 99)
# 14) 14  - (NaN) Don’t know/ Respondents who reported they didn ́t know, were not sure, refused to report or Refused/ Missing had missing responses for their age.


#Interpret Employee Status status as: 
# a) 1 (Employed)
# b) 2 (Self-employed)
# c) 3 (Not Employed >= 1 year)
# d) 4 (Not Employed < 1 year) 
# e) 5 (Homemaker)
# f) 6 (Student)
# g) 7 (Retired)
# h) 8 (Not Employed)
# i) 9,10 (NaN)

reduced_mental_health_data = reduced_mental_health_data.rename(columns={
                                                                    "IDATE"    : "RecordDate", 
                                                                    "_STATE"   : "State", 
                                                                    "_AGEG5YR" : "Age_Range",
                                                                    "SEX"      : "Gender",
                                                                    "_PRACE1"  : "Race",
                                                                    "EMPLOY1"  : "Employment_Status",
                                                                    "MSCODE"   : "MetroStatusCode",
                                                                    "MENTHLTH" : "Mental_Health_Factor",
                                                                    "POORHLTH" : "Poor_Health_Factor",
                                                                    "HLTHPLN1" : "Health_Coverage", 
                                                                    "SLEPTIM1" : "Sleep_Hours",
                                                                    "CVDINFR4" : "Chronic_HeartAttack", 
                                                                    "CVDCRHD4" : "Chronic_CoronaryHeartDisease", 
                                                                    "CVDSTRK3" : "Chronic_Stroke", 
                                                                    "ASTHNOW"  : "Chronic_Asthma", 
                                                                    "CHCSCNCR" : "Chronic_SkinCancer", 
                                                                    "CHCOCNCR" : "Chronic_OtherCancer",
                                                                    "CHCCOPD1" : "Chronic_Pulmonary",
                                                                    "HAVARTH3" : "Chronic_Arthritis",
                                                                    "ADDEPEV2" : "Chronic_Depression", 
                                                                    "CHCKIDNY" : "Chronic_KidneyDisease", 
                                                                    "DIABETE3" : "Chronic_Diabetes", 
                                                                    "PREGNANT" : "Pregnant", 
                                                                    "DECIDE"   : "Difficulty_ConcentrateMemoryDecision", 
                                                                    "DIFFALON" : "Difficulty_ErrandsAlone", 
                                                                    "SMOKDAY2" : "Smoke_Frequency", 
                                                                    "ALCDAY5"  : "Alcohol_Frequency", 
                                                                    "MARIJANA" : "Marijuana_Usage",
                                                                    "EMTSUPRT" : "EmotionalSupport_Availability", 
                                                                    'LSATISFY' : "LifeSatisfaction_Level"
                                                                })

reduced_mental_health_data.head()

,RecordDate,State,Gender,Age_Range,Race,Employment_Status,MetroStatusCode,Mental_Health_Factor,Poor_Health_Factor,Health_Coverage,...,Chronic_KidneyDisease,Chronic_Diabetes,Pregnant,Difficulty_ConcentrateMemoryDecision,Difficulty_ErrandsAlone,Smoke_Frequency,Alcohol_Frequency,Marijuana_Usage,EmotionalSupport_Availability,LifeSatisfaction_Level
0,b'01072016',1.0,1.0,5.0,1.0,1.0,3.0,88.0,NaN,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
1,b'01112016',1.0,2.0,8.0,1.0,5.0,1.0,88.0,NaN,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
2,b'01062016',1.0,2.0,13.0,1.0,7.0,2.0,1.0,88.0,1.0,...,2.0,3.0,NaN,2.0,2.0,1.0,101.0,NaN,NaN,NaN
3,b'01082016',1.0,1.0,11.0,1.0,7.0,1.0,88.0,NaN,1.0,...,2.0,1.0,NaN,2.0,2.0,3.0,888.0,NaN,NaN,NaN
4,b'01052016',1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN

In [6]:
# Find number of records present for the filtered columns in 2016 Data
print (len(reduced_mental_health_data.index))

486303

In [7]:
# Find unique values n each column - Then count them 

reduced_mental_health_data.apply(pd.Series.nunique)

# Write info into a CSV file if possible 

#Compare unique values again in each column and count them to see see if there is any data loss

RecordDate                              419
State                                    54
Gender                                    3
Age_Range                                14
Race                                     10
Employment_Status                         9
MetroStatusCode                           4
Mental_Health_Factor                     33
Poor_Health_Factor                       33
Health_Coverage                           4
Sleep_Hours                              26
Chronic_HeartAttack                       4
Chronic_CoronaryHeartDisease              4
Chronic_Stroke                            4
Chronic_Asthma                            4
Chronic_SkinCancer                        4
Chronic_OtherCancer                       4
Chronic_Pulmonary                         4
Chronic_Arthritis                         4
Chronic_Depression                        4
Chronic_KidneyDisease                     4
Chronic_Diabetes                          6
Pregnant                                  4
Difficulty_ConcentrateMemoryDecision      4
Difficulty_ErrandsAlone                   4
Smoke_Frequency                           5
Alcohol_Frequency                        40
Marijuana_Usage                          33
EmotionalSupport_Availability             7
LifeSatisfaction_Level                    6
dtype: int64

In [3]:
# Write info into a CSV file if possible 

reduced_mental_health_data.to_csv('MentalHealth2015.csv')

#Compare unique values again in each column and count them to see see if there is any data loss 

#read_csv to find un

#mental_health_csv_data.apply(pd.Series.nunique)

NameError: name 'reduced_mental_health_data' is not defined

In [9]:
df2 = pd.read_csv('MentalHealth2015.csv')

df2.head()

,Unnamed: 0,RecordDate,State,Gender,Age_Range,Race,Employment_Status,MetroStatusCode,Mental_Health_Factor,Poor_Health_Factor,...,Chronic_KidneyDisease,Chronic_Diabetes,Pregnant,Difficulty_ConcentrateMemoryDecision,Difficulty_ErrandsAlone,Smoke_Frequency,Alcohol_Frequency,Marijuana_Usage,EmotionalSupport_Availability,LifeSatisfaction_Level
0,0,b'01072016',1.0,1.0,5.0,1.0,1.0,3.0,88.0,NaN,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
1,1,b'01112016',1.0,2.0,8.0,1.0,5.0,1.0,88.0,NaN,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN
2,2,b'01062016',1.0,2.0,13.0,1.0,7.0,2.0,1.0,88.0,...,2.0,3.0,NaN,2.0,2.0,1.0,101.0,NaN,NaN,NaN
3,3,b'01082016',1.0,1.0,11.0,1.0,7.0,1.0,88.0,NaN,...,2.0,1.0,NaN,2.0,2.0,3.0,888.0,NaN,NaN,NaN
4,4,b'01052016',1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,...,2.0,3.0,NaN,2.0,2.0,NaN,888.0,NaN,NaN,NaN

In [10]:
df2.apply(pd.Series.nunique)

Unnamed: 0                              486303
RecordDate                                 419
State                                       54
Gender                                       3
Age_Range                                   14
Race                                        10
Employment_Status                            9
MetroStatusCode                              4
Mental_Health_Factor                        33
Poor_Health_Factor                          33
Health_Coverage                              4
Sleep_Hours                                 26
Chronic_HeartAttack                          4
Chronic_CoronaryHeartDisease                 4
Chronic_Stroke                               4
Chronic_Asthma                               4
Chronic_SkinCancer                           4
Chronic_OtherCancer                          4
Chronic_Pulmonary                            4
Chronic_Arthritis                            4
Chronic_Depression                           4
Chronic_KidneyDisease                        4
Chronic_Diabetes                             6
Pregnant                                     4
Difficulty_ConcentrateMemoryDecision         4
Difficulty_ErrandsAlone                      4
Smoke_Frequency                              5
Alcohol_Frequency                           40
Marijuana_Usage                             33
EmotionalSupport_Availability                7
LifeSatisfaction_Level                       6
dtype: int64